
---
title: "Sample Radar Charts" 
author: "Author: Sarah Allen"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`" 
output:
  html_document:
    toc: true
    toc_float:
        collapsed: true
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    code_folding: show
    number_sections: true

fontsize: 14pt
---

<!---
rscript -e "rmarkdown::render('data.rmd', c('html_document'), clean=FALSE)"
-->
```{r global_options, echo=FALSE, warning=FALSE, message=FALSE}
library(rAmCharts)
library(pipeR)
```

```{r safe, echo=FALSE}
data <- data.frame(label = c("Release Process", "Development Process", "Dependencies", "Vulnerability Comms", "Security Team", "Ecosystem Need", "Adoption"),
                   now = c(4, 4, 4, 1, 1, 4, 1), 
                   soon = c(4, 4, 4, 3, 3, 4, 3))

amRadar(data = data, xlim = c(0, 4), pch = "bubble", export = TRUE) %>>% setLegend(position = "left")

# amRadar(data = data, legend = TRUE, legendPosition = "left", pch = "bubble", export = TRUE) %>>% setLegend(position = "bottom", useMarkerColorForLabels = TRUE)

```

<!---
# Error in legend(position = "left", useMarkerColorForLabels = TRUE) : 
#  unused arguments (position = "left", useMarkerColorForLabels = TRUE)
# when using this syntax from: https://datastorm-open.github.io/introduction_ramcharts/convert.html

legend_obj <- legend(position = "left", useMarkerColorForLabels = TRUE)
amRadar(data = data, legend = legend_obj, pch = "bubble", export = TRUE) 
-->


```{r radar_example, echo=FALSE}
data <- data.frame(label =  c("A", "Z", "E", "R", "T"),
                   Product1 = c(1, 2, 3, 4, 2), 
                   Product2 = c(2, 8, 1, 1, 0),
                   Product3 = c(1,1,2,2,4))
amRadar(data = data)
```